# Generated by Django 4.2.5 on 2023-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POST', 'Posters'), ('MISC', 'Miscellaneous')], max_length=15),
        ),
    ]
